<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraAnimationTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraAnimationTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:simpleType name="Animation">
    <xs:union memberTypes="types:ClipLoop" />
  </xs:simpleType>
  <xs:simpleType name="ClipLoop">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Once" />
      <xs:enumeration value="Loop" />
      <xs:enumeration value="PingPong" />
    </xs:restriction>
  </xs:simpleType>
  <xs:attributeGroup name="Clip.Attributes">
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Loop" type="types:ClipLoop" />
  </xs:attributeGroup>
  <xs:element name="Clip" type="types:Clip" />
  <xs:group name="ClipTrackDefinition.Children">
    <xs:choice>
      <xs:element name="Track" type="types:Track" />
    </xs:choice>
  </xs:group>
  <xs:complexType name="Clip">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:ClipTrackDefinition.Children" />
    </xs:sequence>
    <xs:attributeGroup ref="types:Clip.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="Track.Attributes">
    <xs:attribute name="Property" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="Track" type="types:Track" />
  <xs:group name="KeyDefinition.Children">
    <xs:choice>
      <xs:element name="Key" type="types:Key" />
    </xs:choice>
  </xs:group>
  <xs:complexType name="Track">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:KeyDefinition.Children" />
    </xs:sequence>
    <xs:attributeGroup ref="types:Track.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="Key.Attributes">
    <xs:attribute name="Time" type="xs:float" />
    <xs:attribute name="Value" type="xs:string" />
    <xs:attribute name="Ease" type="xs:string" />
    <xs:attribute name="X1" type="xs:float" />
    <xs:attribute name="Y1" type="xs:float" />
    <xs:attribute name="X2" type="xs:float" />
    <xs:attribute name="Y2" type="xs:float" />
    <xs:attribute name="Steps" type="xs:int" />
  </xs:attributeGroup>
  <xs:element name="Key" type="types:Key" />
  <xs:complexType name="Key">
    <xs:sequence />
    <xs:attributeGroup ref="types:Key.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="Binding.Attributes">
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Frequency" type="xs:float" />
    <xs:attribute name="Damping" type="xs:float" />
  </xs:attributeGroup>
  <xs:element name="Binding" type="types:Binding" />
  <xs:group name="BindingTrackDefinition.Children">
    <xs:choice>
      <xs:element name="BindingTrack" type="types:BindingTrack" />
    </xs:choice>
  </xs:group>
  <xs:complexType name="Binding">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:BindingTrackDefinition.Children" />
    </xs:sequence>
    <xs:attributeGroup ref="types:Binding.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="BindingTrack.Attributes">
    <xs:attribute name="Property" type="xs:string" />
    <xs:attribute name="Rest" type="xs:string" />
    <xs:attribute name="Hover" type="xs:string" />
    <xs:attribute name="Press" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="BindingTrack" type="types:BindingTrack" />
  <xs:complexType name="BindingTrack">
    <xs:sequence />
    <xs:attributeGroup ref="types:BindingTrack.Attributes" />
  </xs:complexType>
  <xs:element name="Animations" type="types:Animations" />
  <xs:group name="AnimationDefinition.Children">
    <xs:choice>
      <xs:element name="Clip" type="types:Clip" />
      <xs:element name="Binding" type="types:Binding" />
    </xs:choice>
  </xs:group>
  <xs:complexType name="Animations">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:AnimationDefinition.Children" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>