<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraSettingsTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" xmlns:Input="http://arctisaurora/AuroraInputTypes" xmlns:UI="http://arctisaurora/AuroraUITypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraSettingsTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:import schemaLocation="InputTypeSchema.xsd" namespace="http://arctisaurora/AuroraInputTypes" />
  <xs:import schemaLocation="UITypeSchema.xsd" namespace="http://arctisaurora/AuroraUITypes" />
  <xs:simpleType name="Settings">
    <xs:union memberTypes="types:SettingScope types:LogLevel types:WindowMode" />
  </xs:simpleType>
  <xs:attributeGroup name="DragGhost.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="Opacity" type="xs:float" />
  </xs:attributeGroup>
  <xs:element name="DragGhost" type="types:DragGhost" />
  <xs:complexType name="DragGhost">
    <xs:sequence />
    <xs:attributeGroup ref="types:DragGhost.Attributes" />
  </xs:complexType>
  <xs:element name="UI" type="types:UI" />
  <xs:group name="Setting.Children">
    <xs:choice>
      <xs:element name="DragGhost" type="types:DragGhost" />
      <xs:element name="LogConsole" type="types:LogConsole" />
      <xs:element name="LogFile" type="types:LogFile" />
      <xs:element name="LogRecorder" type="types:LogRecorder" />
      <xs:element name="DoubleClick" type="types:DoubleClick" />
      <xs:element name="KeyRepeat" type="types:KeyRepeat" />
      <xs:element name="Device" type="types:Device" />
      <xs:element name="Monitor" type="types:Monitor" />
      <xs:element name="Window" type="types:Window" />
      <xs:element name="VSync" type="types:VSync" />
      <xs:element name="Validation" type="types:Validation" />
    </xs:choice>
  </xs:group>
  <xs:complexType name="UI">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:Setting.Children" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DocumentSettings" type="types:DocumentSettings" />
  <xs:complexType name="DocumentSettings">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="DocumentLayout" type="UI:DocumentLayout">
        <xs:annotation>
          <xs:documentation>Editor-wide layout and text styles.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="SettingScope">
    <xs:restriction base="xs:string">
      <xs:enumeration value="App" />
      <xs:enumeration value="User" />
    </xs:restriction>
  </xs:simpleType>
  <xs:attributeGroup name="Setting.Attributes">
    <xs:attribute name="Scope" type="types:SettingScope" />
    <xs:attribute name="OnChanged" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="UserSettings" type="types:UserSettings" />
  <xs:group name="ISettingsGroup.Children">
    <xs:choice>
      <xs:element name="UI" type="types:UI" />
      <xs:element name="DocumentSettings" type="types:DocumentSettings" />
      <xs:element name="Logging" type="types:Logging" />
      <xs:element name="InputBindings" type="types:InputBindings" />
      <xs:element name="Input" type="types:Input" />
      <xs:element name="Graphics" type="types:Graphics" />
    </xs:choice>
  </xs:group>
  <xs:complexType name="UserSettings">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:ISettingsGroup.Children" />
    </xs:sequence>
  </xs:complexType>
  <xs:attributeGroup name="LogConsole.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="MinLevel" type="types:LogLevel" />
  </xs:attributeGroup>
  <xs:element name="LogConsole" type="types:LogConsole" />
  <xs:complexType name="LogConsole">
    <xs:sequence />
    <xs:attributeGroup ref="types:LogConsole.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="LogFile.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="MinLevel" type="types:LogLevel" />
    <xs:attribute name="Directory" type="xs:string" />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="BufferKB" type="xs:int" />
    <xs:attribute name="FlushMs" type="xs:int" />
    <xs:attribute name="MaxFileMB" type="xs:int" />
    <xs:attribute name="Keep" type="xs:int" />
  </xs:attributeGroup>
  <xs:element name="LogFile" type="types:LogFile" />
  <xs:complexType name="LogFile">
    <xs:sequence />
    <xs:attributeGroup ref="types:LogFile.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="LogRecorder.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="Enabled" type="xs:boolean" />
    <xs:attribute name="MinLevel" type="types:LogLevel" />
    <xs:attribute name="CapacityKB" type="xs:int" />
  </xs:attributeGroup>
  <xs:element name="LogRecorder" type="types:LogRecorder" />
  <xs:complexType name="LogRecorder">
    <xs:sequence />
    <xs:attributeGroup ref="types:LogRecorder.Attributes" />
  </xs:complexType>
  <xs:element name="Logging" type="types:Logging" />
  <xs:complexType name="Logging">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:Setting.Children" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="LogLevel">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Hot" />
      <xs:enumeration value="Trace" />
      <xs:enumeration value="Debug" />
      <xs:enumeration value="Info" />
      <xs:enumeration value="Warn" />
      <xs:enumeration value="Error" />
      <xs:enumeration value="Fatal" />
      <xs:enumeration value="Off" />
    </xs:restriction>
  </xs:simpleType>
  <xs:attributeGroup name="Bind.Attributes">
    <xs:attribute name="Action" type="xs:string" />
    <xs:attribute name="Trigger" type="Input:Keys" />
    <xs:attribute name="Modifiers" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="Bind" type="types:Bind" />
  <xs:complexType name="Bind">
    <xs:sequence />
    <xs:attributeGroup ref="types:Bind.Attributes" />
  </xs:complexType>
  <xs:element name="InputBindings" type="types:InputBindings" />
  <xs:group name="KeybindOverride.Children">
    <xs:choice>
      <xs:element name="Bind" type="types:Bind" />
    </xs:choice>
  </xs:group>
  <xs:complexType name="InputBindings">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:KeybindOverride.Children" />
    </xs:sequence>
  </xs:complexType>
  <xs:attributeGroup name="DoubleClick.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="Timeout" type="xs:float" />
  </xs:attributeGroup>
  <xs:element name="DoubleClick" type="types:DoubleClick" />
  <xs:complexType name="DoubleClick">
    <xs:sequence />
    <xs:attributeGroup ref="types:DoubleClick.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="KeyRepeat.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="Delay" type="xs:float" />
    <xs:attribute name="Rate" type="xs:float" />
  </xs:attributeGroup>
  <xs:element name="KeyRepeat" type="types:KeyRepeat" />
  <xs:complexType name="KeyRepeat">
    <xs:sequence />
    <xs:attributeGroup ref="types:KeyRepeat.Attributes" />
  </xs:complexType>
  <xs:element name="Input" type="types:Input" />
  <xs:complexType name="Input">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:Setting.Children" />
    </xs:sequence>
  </xs:complexType>
  <xs:attributeGroup name="Device.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="Name" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="Device" type="types:Device" />
  <xs:complexType name="Device">
    <xs:sequence />
    <xs:attributeGroup ref="types:Device.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="Monitor.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="Name" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="Monitor" type="types:Monitor" />
  <xs:complexType name="Monitor">
    <xs:sequence />
    <xs:attributeGroup ref="types:Monitor.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="Window.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="Mode" type="types:WindowMode" />
    <xs:attribute name="Width" type="xs:unsignedInt" />
    <xs:attribute name="Height" type="xs:unsignedInt" />
  </xs:attributeGroup>
  <xs:element name="Window" type="types:Window" />
  <xs:complexType name="Window">
    <xs:sequence />
    <xs:attributeGroup ref="types:Window.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="VSync.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="On" type="xs:boolean" />
  </xs:attributeGroup>
  <xs:element name="VSync" type="types:VSync" />
  <xs:complexType name="VSync">
    <xs:sequence />
    <xs:attributeGroup ref="types:VSync.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="Validation.Attributes">
    <xs:attributeGroup ref="types:Setting.Attributes" />
    <xs:attribute name="Enabled" type="xs:boolean" />
    <xs:attribute name="Synchronization" type="xs:boolean" />
    <xs:attribute name="BestPractices" type="xs:boolean" />
    <xs:attribute name="GpuAssisted" type="xs:boolean" />
    <xs:attribute name="MinLevel" type="types:LogLevel" />
  </xs:attributeGroup>
  <xs:element name="Validation" type="types:Validation" />
  <xs:complexType name="Validation">
    <xs:sequence />
    <xs:attributeGroup ref="types:Validation.Attributes" />
  </xs:complexType>
  <xs:element name="Graphics" type="types:Graphics" />
  <xs:complexType name="Graphics">
    <xs:sequence>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="types:Setting.Children" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="WindowMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Windowed" />
      <xs:enumeration value="Borderless" />
      <xs:enumeration value="Fullscreen" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>