<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraAssetRegistryTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraAssetRegistryTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:element name="IParseableTypes" type="types:IParseableTypes" />
  <xs:complexType name="IParseableTypes">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="FontAsset" type="types:FontAsset" />
  <xs:complexType name="FontAsset">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="IconSetAsset" type="types:IconSetAsset" />
  <xs:complexType name="IconSetAsset">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="TextureAsset" type="types:TextureAsset" />
  <xs:complexType name="TextureAsset">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="UIDocumentAsset" type="types:UIDocumentAsset" />
  <xs:complexType name="UIDocumentAsset">
    <xs:sequence />
  </xs:complexType>
  <xs:attributeGroup name="Charset.Attributes">
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Chars" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="Charset" type="types:Charset" />
  <xs:complexType name="Charset">
    <xs:sequence />
    <xs:attributeGroup ref="types:Charset.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="FontImport.Attributes">
    <xs:attribute name="Source" type="xs:string" />
    <xs:attribute name="Bold" type="xs:string" />
    <xs:attribute name="Italic" type="xs:string" />
    <xs:attribute name="BoldItalic" type="xs:string" />
    <xs:attribute name="Charset" type="xs:string" />
    <xs:attribute name="GlyphSize" type="xs:int" />
  </xs:attributeGroup>
  <xs:element name="FontImport" type="types:FontImport" />
  <xs:complexType name="FontImport">
    <xs:sequence />
    <xs:attributeGroup ref="types:FontImport.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="IconImport.Attributes">
    <xs:attribute name="Source" type="xs:string" />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="IconSize" type="xs:int" />
  </xs:attributeGroup>
  <xs:element name="IconImport" type="types:IconImport" />
  <xs:complexType name="IconImport">
    <xs:sequence />
    <xs:attributeGroup ref="types:IconImport.Attributes" />
  </xs:complexType>
  <xs:element name="ImportSet" type="types:ImportSet" />
  <xs:complexType name="ImportSet">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Charset" type="types:Charset">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="FontImport" type="types:FontImport">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="IconImport" type="types:IconImport">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="AVulkanMesh" type="types:AVulkanMesh" />
  <xs:complexType name="AVulkanMesh">
    <xs:sequence />
  </xs:complexType>
  <xs:attributeGroup name="AssetEntry.Attributes">
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="KeyType" type="allTypes:Uncategorized" />
    <xs:attribute name="ValueType" type="allTypes:Uncategorized" />
  </xs:attributeGroup>
  <xs:element name="AssetEntry" type="types:AssetEntry" />
  <xs:complexType name="AssetEntry">
    <xs:sequence />
    <xs:attributeGroup ref="types:AssetEntry.Attributes" />
  </xs:complexType>
  <xs:attributeGroup name="Asset.Attributes">
    <xs:attribute name="Type" type="xs:string" />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Source" type="xs:string" />
  </xs:attributeGroup>
  <xs:element name="Asset" type="types:Asset" />
  <xs:complexType name="Asset">
    <xs:sequence />
    <xs:attributeGroup ref="types:Asset.Attributes" />
  </xs:complexType>
  <xs:element name="AssetRegistries" type="types:AssetRegistries" />
  <xs:complexType name="AssetRegistries">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Dictionary" type="types:AssetEntry">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ControlStyle" type="types:ControlStyle" />
  <xs:complexType name="ControlStyle">
    <xs:sequence />
  </xs:complexType>
</xs:schema>