<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraSettingsTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" xmlns:UI="http://arctisaurora/AuroraUITypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraSettingsTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:import schemaLocation="UITypeSchema.xsd" namespace="http://arctisaurora/AuroraUITypes" />
  <xs:simpleType name="Settings">
    <xs:union memberTypes="types:SettingScope types:WindowMode" />
  </xs:simpleType>
  <xs:element name="Vault" type="types:Vault" />
  <xs:complexType name="Vault">
    <xs:sequence />
    <xs:attribute name="Path" type="xs:string" />
    <xs:attribute name="Scope" type="types:SettingScope" />
    <xs:attribute name="OnChanged" type="xs:string" />
  </xs:complexType>
  <xs:element name="Periodic" type="types:Periodic" />
  <xs:complexType name="Periodic">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Vault" type="types:Vault" />
        <xs:element name="DragGhost" type="types:DragGhost" />
        <xs:element name="DoubleClick" type="types:DoubleClick" />
        <xs:element name="KeyRepeat" type="types:KeyRepeat" />
        <xs:element name="Device" type="types:Device" />
        <xs:element name="Monitor" type="types:Monitor" />
        <xs:element name="Window" type="types:Window" />
        <xs:element name="VSync" type="types:VSync" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DragGhost" type="types:DragGhost" />
  <xs:complexType name="DragGhost">
    <xs:sequence />
    <xs:attribute name="Opacity" type="xs:float" />
    <xs:attribute name="Scope" type="types:SettingScope" />
    <xs:attribute name="OnChanged" type="xs:string" />
  </xs:complexType>
  <xs:element name="UI" type="types:UI" />
  <xs:complexType name="UI">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Vault" type="types:Vault" />
        <xs:element name="DragGhost" type="types:DragGhost" />
        <xs:element name="DoubleClick" type="types:DoubleClick" />
        <xs:element name="KeyRepeat" type="types:KeyRepeat" />
        <xs:element name="Device" type="types:Device" />
        <xs:element name="Monitor" type="types:Monitor" />
        <xs:element name="Window" type="types:Window" />
        <xs:element name="VSync" type="types:VSync" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DocumentSettings" type="types:DocumentSettings" />
  <xs:complexType name="DocumentSettings">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="DocumentLayout" type="UI:DocumentLayout">
        <xs:annotation>
          <xs:documentation>Editor-wide layout and text styles.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="SettingScope">
    <xs:restriction base="xs:string">
      <xs:enumeration value="App" />
      <xs:enumeration value="User" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="UserSettings" type="types:UserSettings" />
  <xs:complexType name="UserSettings">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Periodic" type="types:Periodic" />
        <xs:element name="UI" type="types:UI" />
        <xs:element name="DocumentSettings" type="types:DocumentSettings" />
        <xs:element name="Input" type="types:Input" />
        <xs:element name="Graphics" type="types:Graphics" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DoubleClick" type="types:DoubleClick" />
  <xs:complexType name="DoubleClick">
    <xs:sequence />
    <xs:attribute name="Timeout" type="xs:float" />
    <xs:attribute name="Scope" type="types:SettingScope" />
    <xs:attribute name="OnChanged" type="xs:string" />
  </xs:complexType>
  <xs:element name="KeyRepeat" type="types:KeyRepeat" />
  <xs:complexType name="KeyRepeat">
    <xs:sequence />
    <xs:attribute name="Delay" type="xs:float" />
    <xs:attribute name="Rate" type="xs:float" />
    <xs:attribute name="Scope" type="types:SettingScope" />
    <xs:attribute name="OnChanged" type="xs:string" />
  </xs:complexType>
  <xs:element name="Input" type="types:Input" />
  <xs:complexType name="Input">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Vault" type="types:Vault" />
        <xs:element name="DragGhost" type="types:DragGhost" />
        <xs:element name="DoubleClick" type="types:DoubleClick" />
        <xs:element name="KeyRepeat" type="types:KeyRepeat" />
        <xs:element name="Device" type="types:Device" />
        <xs:element name="Monitor" type="types:Monitor" />
        <xs:element name="Window" type="types:Window" />
        <xs:element name="VSync" type="types:VSync" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Device" type="types:Device" />
  <xs:complexType name="Device">
    <xs:sequence />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Scope" type="types:SettingScope" />
    <xs:attribute name="OnChanged" type="xs:string" />
  </xs:complexType>
  <xs:element name="Monitor" type="types:Monitor" />
  <xs:complexType name="Monitor">
    <xs:sequence />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Scope" type="types:SettingScope" />
    <xs:attribute name="OnChanged" type="xs:string" />
  </xs:complexType>
  <xs:element name="Window" type="types:Window" />
  <xs:complexType name="Window">
    <xs:sequence />
    <xs:attribute name="Mode" type="types:WindowMode" />
    <xs:attribute name="Width" type="xs:unsignedInt" />
    <xs:attribute name="Height" type="xs:unsignedInt" />
    <xs:attribute name="Scope" type="types:SettingScope" />
    <xs:attribute name="OnChanged" type="xs:string" />
  </xs:complexType>
  <xs:element name="VSync" type="types:VSync" />
  <xs:complexType name="VSync">
    <xs:sequence />
    <xs:attribute name="On" type="xs:boolean" />
    <xs:attribute name="Scope" type="types:SettingScope" />
    <xs:attribute name="OnChanged" type="xs:string" />
  </xs:complexType>
  <xs:element name="Graphics" type="types:Graphics" />
  <xs:complexType name="Graphics">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Vault" type="types:Vault" />
        <xs:element name="DragGhost" type="types:DragGhost" />
        <xs:element name="DoubleClick" type="types:DoubleClick" />
        <xs:element name="KeyRepeat" type="types:KeyRepeat" />
        <xs:element name="Device" type="types:Device" />
        <xs:element name="Monitor" type="types:Monitor" />
        <xs:element name="Window" type="types:Window" />
        <xs:element name="VSync" type="types:VSync" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="WindowMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Windowed" />
      <xs:enumeration value="Borderless" />
      <xs:enumeration value="Fullscreen" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>